@BaseUrl=https://localhost:5001/api/v1/Carts
@KayToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbW9iaWxlcGhvbmUiOiIwNTU3NTExNjc3IiwianRpIjoiYjc2YTE4NWUiLCJhdWQiOiJodHRwczovL2xvY2FsaG9zdDo1MDAxIiwibmJmIjoxNjkzMTYzMDQ5LCJleHAiOjE2OTMxNjQ4NDksImlhdCI6MTY5MzE2MzA0OSwiaXNzIjoiaHVidGVsLWNhcnQtYXBpIn0.RgBcZbHrlaOXLSzBTzp4uuX7Jx_ApNAug28VQi_DyLs
@HubtelToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJIdWJ0ZWwiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9tb2JpbGVwaG9uZSI6IjA1NTc1MTE2NzciLCJqdGkiOiJkNGFhZGY1NiIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjUwMDEiLCJuYmYiOjE2OTMyNDIyODAsImV4cCI6MTY5MzI0NDA4MCwiaWF0IjoxNjkzMjQyMjgwLCJpc3MiOiJodWJ0ZWwtY2FydC1hcGkifQ.5qpxGHUQgFdFHU0fxcHNFsoJxLd9WTzLcKAJz20Qwd0
@ItemId=4

###
POST {{BaseUrl}}
Content-Type: application/json
Authorization: Bearer {{HubtelToken}}

{
  "items": [
    {
      "itemId": {{ItemId}},
      "quantity": 25
    }
  ]
}

###
DELETE {{BaseUrl}}/{{ItemId}}
Authorization: Bearer {{HubtelToken}}

###
GET {{BaseUrl}}/items?phone=&time=2023-08-27&quantity=&itemName=

###
GET {{BaseUrl}}?filter=invalidfilter
Authorization: Bearer {{HubtelToken}}

###
GET {{BaseUrl}}?filter=
Authorization: Bearer {{HubtelToken}}