@BaseUrl=https://localhost:5001/api/v1/Users

###
POST {{BaseUrl}}/Login
Content-Type: application/json

{
    "email": "hubtel@gmail.com",
    "password": "NewPassword@cart1"
}

###
POST {{BaseUrl}}/Login
Content-Type: application/json

{
    "email": "kofigyasidev@gmail.com",
    "password": "NewPassword@cart1"
}
